/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ascompliancereport.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.cisco.as.reusable.actions.ascompliancereports.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ascompliancereport.yang */
public class ascompliancereport extends ConfNamespace {
    public static final int hash = 2108297566;
    public int hash() {
        return ascompliancereport.hash;
    }

    public static final String id = "http://com/cisco/as/reusable/actions/ascompliancereports";
    public String id() {
        return ascompliancereport.id;
    }

    public static final String uri = "http://com/cisco/as/reusable/actions/ascompliancereports";
    public String uri() {
        return ascompliancereport.uri;
    }

    public static final String prefix = "ascompliancereport";
    public String prefix() {
        return ascompliancereport.prefix;
    }

    public ascompliancereport() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _outformat = 2033658489;
    public static final String _outformat_ = "outformat";
    public static final int    _device_name = 221570148;
    public static final String _device_name_ = "device-name";
    public static final int    _report_name = 358846334;
    public static final String _report_name_ = "report-name";
    public static final int    _compliance_reports = 1989448417;
    public static final String _compliance_reports_ = "compliance-reports";
    public static final int    _devices = 270307409;
    public static final String _devices_ = "devices";
    public static final int    _url = 1560781157;
    public static final String _url_ = "url";
    public static final int    _generate_compliance_report = 1283457760;
    public static final String _generate_compliance_report_ = "generate-compliance-report";
    public static final int    _templates = 851652025;
    public static final String _templates_ = "templates";
    public static final int    _make_complaint = 388461568;
    public static final String _make_complaint_ = "make-complaint";
    public static final int    _jobname = 1706570863;
    public static final String _jobname_ = "jobname";
    public static final int    _report_title = 1255268718;
    public static final String _report_title_ = "report-title";
    public static final int    _error_message = 174234492;
    public static final String _error_message_ = "error-message";
    public static final int    _template_name = 448823355;
    public static final String _template_name_ = "template-name";
    public static final String actionpoint_generate_compliance_report_action_point = "generate-compliance-report-action-point";
}
